// This file is automatically generated. Do not edit it directly.
import { createClient, type Session } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error(
    "Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your .env file",
  );
}

const AUTH_STORAGE_KEY = "sb-auth-session";
const ACCESS_TOKEN_COOKIE = "sb-access-token";
const REFRESH_TOKEN_COOKIE = "sb-refresh-token";
const EXPIRES_AT_COOKIE = "sb-token-expires-at";
const THIRTY_DAYS_IN_SECONDS = 60 * 60 * 24 * 30;

const isBrowser = typeof document !== "undefined";

const cleanLegacyStorage = () => {
  if (!isBrowser) return;
  try {
    const keys = Object.keys(localStorage);
    keys.forEach((key) => {
      if (key.includes("supabase") || key.includes("auth")) {
        localStorage.removeItem(key);
      }
    });
  } catch (error) {
    console.warn("Unable to inspect localStorage for legacy tokens", error);
  }
};

cleanLegacyStorage();

const getCookieValue = (name: string) => {
  if (!isBrowser || !document.cookie) return null;
  const cookies = document.cookie.split("; ");
  for (const cookie of cookies) {
    const [cookieName, ...rest] = cookie.split("=");
    if (cookieName === name) {
      return decodeURIComponent(rest.join("="));
    }
  }
  return null;
};

const isSecureContext = () => {
  if (typeof window === "undefined") return false;
  return window.location.protocol === "https:";
};

const baseCookieOptions = () => {
  const options = ["Path=/", "SameSite=Strict"];
  if (isSecureContext()) {
    options.push("Secure");
  }
  return options.join("; ");
};

const setBrowserCookie = (name: string, value: string, maxAge?: number) => {
  if (!isBrowser) return;
  const options = [baseCookieOptions()];
  if (typeof maxAge === "number") {
    options.push(`Max-Age=${Math.max(0, Math.floor(maxAge))}`);
  }
  document.cookie = `${name}=${encodeURIComponent(value)}; ${options.join("; ")}`;
};

const removeBrowserCookie = (name: string) => {
  if (!isBrowser) return;
  document.cookie = `${name}=; ${baseCookieOptions()}; Max-Age=0`;
};

const parseSession = (raw: string): Session | null => {
  try {
    return JSON.parse(raw) as Session;
  } catch {
    return null;
  }
};

const deriveSessionMaxAge = (session: Session | null) => {
  const nowSeconds = Math.floor(Date.now() / 1000);
  if (!session?.expires_at) {
    return 60 * 60; // 1 hour fallback
  }
  return Math.max(session.expires_at - nowSeconds, 60);
};

const syncTokenCookies = (session: Session | null) => {
  if (!session) {
    removeBrowserCookie(ACCESS_TOKEN_COOKIE);
    removeBrowserCookie(REFRESH_TOKEN_COOKIE);
    removeBrowserCookie(EXPIRES_AT_COOKIE);
    return;
  }

  const accessTokenMaxAge = deriveSessionMaxAge(session);
  setBrowserCookie(ACCESS_TOKEN_COOKIE, session.access_token, accessTokenMaxAge);
  if (session.refresh_token) {
    setBrowserCookie(REFRESH_TOKEN_COOKIE, session.refresh_token, THIRTY_DAYS_IN_SECONDS);
  }
  if (session.expires_at) {
    setBrowserCookie(EXPIRES_AT_COOKIE, String(session.expires_at), accessTokenMaxAge);
  }
};

export const cookieStorage = {
  getItem: (key: string) => getCookieValue(key),
  setItem: (key: string, value: string) => {
    if (!value) return;
    if (key === AUTH_STORAGE_KEY) {
      const session = parseSession(value);
      const maxAge = deriveSessionMaxAge(session);
      setBrowserCookie(key, value, maxAge);
      syncTokenCookies(session);
    } else {
      setBrowserCookie(key, value, THIRTY_DAYS_IN_SECONDS);
    }
  },
  removeItem: (key: string) => {
    removeBrowserCookie(key);
    if (key === AUTH_STORAGE_KEY) {
      syncTokenCookies(null);
    }
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: cookieStorage,
    storageKey: AUTH_STORAGE_KEY,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
    flowType: "pkce",
  },
});
